# Import Libraries

In [108]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

# Data Collection and Analysis

## PIMA Kidney Disease Dataset

In [109]:
# load the dataset
kidney_data = pd.read_csv("/Users/macbookpro/Desktop/ML & DL & GENAI Projects/Machine Learning/ Kidney Disease Predictive System/kidney_disease_dataset.csv")
kidney_data

,Age,Creatinine_Level,BUN,Diabetes,Hypertension,GFR,Urine_Output,CKD_Status,Dialysis_Needed
0,71,0.30,40.9,0,1,46.8,1622.0,1,0
1,34,1.79,17.1,0,0,43.8,1428.0,1,0
2,80,2.67,15.0,0,1,78.2,1015.0,1,0
3,40,0.97,31.1,0,1,92.8,1276.0,1,0
4,43,2.05,22.8,1,1,62.2,1154.0,0,0
...,...,...,...,...,...,...,...,...,...
2299,89,1.11,5.0,1,0,55.1,1344.0,1,0
2300,89,0.30,5.0,0,0,47.5,2156.0,1,0
2301,84,0.30,7.3,1,0,120.0,1353.0,0,0
2302,24,1.58,26.4,1,0,75.6,1067.0,0,0
2303,21,0.63,27.1,1,0,50.7,393.0,1,0

In [110]:
# first 5 rows of the dataset
kidney_data.head()

,Age,Creatinine_Level,BUN,Diabetes,Hypertension,GFR,Urine_Output,CKD_Status,Dialysis_Needed
0,71,0.30,40.9,0,1,46.8,1622.0,1,0
1,34,1.79,17.1,0,0,43.8,1428.0,1,0
2,80,2.67,15.0,0,1,78.2,1015.0,1,0
3,40,0.97,31.1,0,1,92.8,1276.0,1,0
4,43,2.05,22.8,1,1,62.2,1154.0,0,0

In [111]:
# number of rows of the dataset
kidney_data.shape

(2304, 9)

In [112]:
# get the statistical measures of the dataset
kidney_data.describe()

,Age,Creatinine_Level,BUN,Diabetes,Hypertension,GFR,Urine_Output,CKD_Status,Dialysis_Needed
count,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000
mean,54.159288,1.305638,18.813672,0.406684,0.498264,68.953863,1309.189670,0.508681,0.013455
std,20.513729,0.789594,10.508358,0.491322,0.500106,24.660191,491.951914,0.500033,0.115237
min,20.000000,0.300000,5.000000,0.000000,0.000000,5.000000,100.000000,0.000000,0.000000
25%,36.000000,0.620000,9.975000,0.000000,0.000000,51.300000,967.750000,0.000000,0.000000
50%,54.000000,1.240000,18.200000,0.000000,0.000000,69.150000,1295.500000,1.000000,0.000000
75%,72.000000,1.842500,26.000000,1.000000,1.000000,86.300000,1633.500000,1.000000,0.000000
max,90.000000,4.130000,61.900000,1.000000,1.000000,120.000000,2899.000000,1.000000,1.000000

In [113]:
kidney_data['Dialysis_Needed'].value_counts()

Dialysis_Needed
0    2273
1      31
Name: count, dtype: int64

### 0 ==> No Dialysis
### 1 ==> Dialysis Present

In [114]:
# separating features and the target
X = kidney_data.drop(columns= 'Dialysis_Needed', axis=1)
y = kidney_data['Dialysis_Needed']

In [115]:
print(X)

      Age  Creatinine_Level   BUN  Diabetes  Hypertension    GFR  \
0      71              0.30  40.9         0             1   46.8
1      34              1.79  17.1         0             0   43.8
2      80              2.67  15.0         0             1   78.2
3      40              0.97  31.1         0             1   92.8
4      43              2.05  22.8         1             1   62.2
...   ...               ...   ...       ...           ...    ...
2299   89              1.11   5.0         1             0   55.1
2300   89              0.30   5.0         0             0   47.5
2301   84              0.30   7.3         1             0  120.0
2302   24              1.58  26.4         1             0   75.6
2303   21              0.63  27.1         1             0   50.7

      Urine_Output  CKD_Status
0           1622.0           1
1           1428.0           1
2           1015.0           1
3           1276.0           1
4           1154.0           0
...            ...         ...
2299        1344.0           1
2300        2156.0           1
2301        1353.0           0
2302        1067.0           0
2303         393.0           1

[2304 rows x 8 columns]

In [116]:
print(y)

0       0
1       0
2       0
3       0
4       0
       ..
2299    0
2300    0
2301    0
2302    0
2303    0
Name: Dialysis_Needed, Length: 2304, dtype: int64

# Data Splitting

In [117]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, stratify=y, random_state=42)

In [118]:
print(X.shape, X_train.shape, X_test.shape)

(2304, 8) (1612, 8) (692, 8)

# Model Training

In [119]:
# train the model
classifier =  svm.SVC(kernel='linear')

In [120]:
# fit the model
classifier.fit(X_train, y_train)

SVC(kernel='linear')

# Model Evaluation

## Accuracy Score

In [121]:
# finding the accuracy score on the training data
X_train_pred = classifier.predict(X_train)
train_data_acc = accuracy_score(X_train_pred, y_train)

In [122]:
# print the accuracy score on the training data
print("The Accuracy Score on the Training Data is: ", train_data_acc)

The Accuracy Score on the Training Data is:  1.0

In [123]:
# print the accuracy on the testing data
X_test_pred = classifier.predict(X_test)
test_data_acc = accuracy_score(X_test_pred, y_test)

In [124]:
# print the accuracy score on the testing data
print("The Accuracy Score on the Testing Score is: ", test_data_acc)

The Accuracy Score on the Testing Score is:  0.9985549132947977

# Building the Predictive System

In [129]:
input_data = (71,0.3,40.9,0,1,46.8,1622,1) # No Dialysis Present
# input_data = (28,1.55,14.5,1,0,73.4,1096,0) # Dialysis Present
# change the input data into a numpy array
input_data_as_numpy_array = np.asarray(input_data)
# reshape thr array as we predict for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
prediction = classifier.predict(input_data_reshaped)
print(prediction)
# make a predictive approach
if (prediction[0] == 0):
    print("No Dialysis Present")
# elif (prediction[1] == 1):
#     print("Dialysis Present")
else:
    print("Dialysis Present")

[0]
No Dialysis Present

/opt/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [130]:
# input_data = (71,0.3,40.9,0,1,46.8,1622,1) # No Dialysis Present
input_data = (28,1.55,14.5,1,0,73.4,1096,0) # Dialysis Present
# change the input data into a numpy array
input_data_as_numpy_array = np.asarray(input_data)
# reshape thr array as we predict for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
prediction = classifier.predict(input_data_reshaped)
print(prediction)
# make a predictive approach
if (prediction[0] == 1):
    print("No Dialysis Present")
# elif (prediction[1] == 1):
#     print("Dialysis Present")
else:
    print("Dialysis Present")

[0]
Dialysis Present

/opt/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

# Save the trained model

In [132]:
# load the pickle library
import pickle

In [133]:
# write model file name
filename = 'kidney_model_data.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [134]:
# load the save model
loaded_model = pickle.load(open('kidney_model_data.sav', 'rb'))